export const AcuClinicSeedLibrary = [
    { name: 'Migraine', malayalam: 'കൊടിഞ്ഞി', usage_count: 1 },
    { name: 'Lower Back Pain', malayalam: 'നടുവേദന', usage_count: 1 },
    { name: 'Neck Pain', malayalam: 'കഴുത്തുവേദന കഴുത്ത്', usage_count: 1 },
    { name: 'Shoulder Pain', malayalam: 'തോളുവേദന തോൾ', usage_count: 1 },
    { name: 'Arm Pain', malayalam: 'കൈവേദന', usage_count: 1 },
    { name: 'Leg Pain', malayalam: 'കാല്‍വേദന കാൽ', usage_count: 1 },
    { name: 'Knee Pain', malayalam: 'മുട്ടുവേദന മുട്ട്', usage_count: 1 },
    { name: 'Difficulty Bending Knee', malayalam: 'മുട്ട് മടക്കാൻ ബുദ്ധിമുട്ട്', usage_count: 1 },
    { name: 'Hip Pain', malayalam: 'ഇടുപ്പുവേദന', usage_count: 1 },
    { name: 'Heel Pain', malayalam: 'ഉപ്പൂറ്റി വേദന', usage_count: 1 },
    { name: 'Heel Spur', malayalam: 'ഉപ്പൂറ്റി ആണി', usage_count: 1 },
    { name: 'Sciatica', malayalam: 'സയാറ്റിക്ക', usage_count: 1 },
    { name: 'Joint Pain', malayalam: 'സന്ധിവേദന', usage_count: 1 },
    { name: 'Elbow Pain', malayalam: 'മുട്ട് വേദന (കൈ)', usage_count: 1 },
    { name: 'Muscle Spasm', malayalam: 'പേശിവേദന കോച്ചിപ്പിടുത്തം', usage_count: 1 },
    { name: 'Superficial Muscle Pain', malayalam: 'പുറമേയുള്ള പേശിവേദന', usage_count: 1 },
    { name: 'Tharippu', malayalam: 'തരിപ്പ്', usage_count: 1 },
    { name: 'Nerve Weakness', malayalam: 'ഞരമ്പ് തളർച്ച', usage_count: 1 },
    { name: 'Hand Nerve Weakness', malayalam: 'കൈ ഞരമ്പ് തളർച്ച', usage_count: 1 },
    { name: 'Leg Involuntary Movement', malayalam: 'കാൽ വിറയൽ', usage_count: 1 },
    { name: 'Head Crawling Sensation', malayalam: 'തലയിൽ ഇഴയുന്ന തോന്നൽ', usage_count: 1 },
    { name: 'Left Arm Movement Difficulty', malayalam: 'ഇടതുകൈ അനക്കാൻ ബുദ്ധിമുട്ട്', usage_count: 1 },
    { name: 'Memory Issues', malayalam: 'ഓർമക്കുറവ്', usage_count: 1 },
    { name: 'High Blood Pressure', malayalam: 'രക്താതിമർദ്ദം ബിപി', usage_count: 1 },
    { name: 'Blood Sugar Imbalance', malayalam: 'പ്രമേഹം ഷുഗർ', usage_count: 1 },
    { name: 'Thyroid Imbalance', malayalam: 'തൈറോയ്ഡ്', usage_count: 1 },
    { name: 'Weight Gain', malayalam: 'അമിതഭാരം', usage_count: 1 },
    { name: 'Fatty Liver', malayalam: 'ഫാറ്റി ലിവർ', usage_count: 1 },
    { name: 'Low Uric Acid', malayalam: 'കുറഞ്ഞ യൂറിക് ആസിഡ്', usage_count: 1 },
    { name: 'Sneezing', malayalam: 'തുമ്മൽ', usage_count: 1 },
    { name: 'Common Cold', malayalam: 'ജലദോഷം', usage_count: 1 },
    { name: 'Breathing Difficulty', malayalam: 'ശ്വസിക്കാൻ ബുദ്ധിമുട്ട് ശ്വാസതടസ്സം', usage_count: 1 },
    { name: 'Dry Throat', malayalam: 'തൊണ്ട വരളുക', usage_count: 1 },
    { name: 'Throat Pain', malayalam: 'തൊണ്ട വേദന', usage_count: 1 },
    { name: 'Ovarian Cyst', malayalam: 'ഓവേറിയൻ സിസ്റ്റ്', usage_count: 1 },
    { name: 'Menstrual Clots', malayalam: 'ആർത്തവ തടസ്സം', usage_count: 1 },
    { name: 'Menstrual Inflammation', malayalam: 'ആർത്തവ വേദന', usage_count: 1 },
    { name: 'Urinary Incontinence', malayalam: 'മൂത്രക്കടച്ചിൽ', usage_count: 1 },
    { name: 'Piles', malayalam: 'മൂലക്കുരു', usage_count: 1 },
    { name: 'Gas Trouble', malayalam: 'ഗ്യാസ് ട്രബിൾ', usage_count: 1 },
    { name: 'Abdominal Pulling Pain', malayalam: 'വയറുവേദന', usage_count: 1 },
    { name: 'Hernia', malayalam: 'ഹെർണിയ', usage_count: 1 },
    { name: 'Constipation', malayalam: 'മലബന്ധം', usage_count: 1 },
    { name: 'Varicose Veins', malayalam: 'വാരിക്കോസ് വെയിൻ', usage_count: 1 },
    { name: 'Leg Edema', malayalam: 'കാൽ നീര്', usage_count: 1 },
    { name: 'Leg Itching', malayalam: 'കാൽ ചൊറിച്ചിൽ', usage_count: 1 },
    { name: 'Toe Deformity', malayalam: 'വിരൽ കോട്ടൽ', usage_count: 1 },
    { name: 'Distance Vision Blur', malayalam: 'കാഴ്ച മങ്ങൽ', usage_count: 1 },
    { name: 'Vision Dimness', malayalam: 'മങ്ങിയ കാഴ്ച', usage_count: 1 },
    { name: 'Eye Irritation', malayalam: 'കണ്ണ് ചൊറിച്ചിൽ', usage_count: 1 },
    { name: 'Impotence', malayalam: 'നപുംസകത്വം', usage_count: 1 },
    { name: 'Headache', malayalam: 'തലവേദന', usage_count: 1 }
];
